resource_groups:
  - name: prod-terragruntapp-rg-01
    location: centralindia
    resource_tags: 
      Application: TerragruntApp
  - name: prod-terragruntapp-rg-02
    location: centralindia
    resource_tags: 
      Application: TerragruntApp
storage_accounts:
  - name: cldprodrgtgapp01
    resource_group_name: prod-terragruntapp-rg-01
    location: centralindia
    account_tier: Standard
    account_replication_type: LRS
    resource_tags:
      Application: TerragruntApp
  - name: cldprodrgtgapp02
    resource_group_name: prod-terragruntapp-rg-02
    location: centralindia
    account_tier: Standard
    account_replication_type: LRS
    resource_tags:
      Application: TerragruntApp